/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIntegrationsWhatsappRouteImport } from './routes/modules.integrations-whatsapp'
import { Route as ModulesModuleRouteImport } from './routes/modules.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIntegrationsWhatsappRoute =
  ModulesIntegrationsWhatsappRouteImport.update({
    id: '/modules/integrations-whatsapp',
    path: '/modules/integrations-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modules/$module' | '/modules/integrations-whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modules/$module' | '/modules/integrations-whatsapp'
  id: '__root__' | '/' | '/modules/$module' | '/modules/integrations-whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
  ModulesIntegrationsWhatsappRoute: typeof ModulesIntegrationsWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/integrations-whatsapp': {
      id: '/modules/integrations-whatsapp'
      path: '/modules/integrations-whatsapp'
      fullPath: '/modules/integrations-whatsapp'
      preLoaderRoute: typeof ModulesIntegrationsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesModuleRoute: ModulesModuleRoute,
  ModulesIntegrationsWhatsappRoute: ModulesIntegrationsWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
