/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesTemplatesWhatsappRouteImport } from './routes/modules.templates-whatsapp'
import { Route as ModulesTemplatesSmsRouteImport } from './routes/modules.templates-sms'
import { Route as ModulesTemplatesEmailRouteImport } from './routes/modules.templates-email'
import { Route as ModulesIntegrationsWhatsappRouteImport } from './routes/modules.integrations-whatsapp'
import { Route as ModulesEventsRouteImport } from './routes/modules.events'
import { Route as ModulesModuleRouteImport } from './routes/modules.$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesTemplatesWhatsappRoute =
  ModulesTemplatesWhatsappRouteImport.update({
    id: '/modules/templates-whatsapp',
    path: '/modules/templates-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesTemplatesSmsRoute = ModulesTemplatesSmsRouteImport.update({
  id: '/modules/templates-sms',
  path: '/modules/templates-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesTemplatesEmailRoute = ModulesTemplatesEmailRouteImport.update({
  id: '/modules/templates-email',
  path: '/modules/templates-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIntegrationsWhatsappRoute =
  ModulesIntegrationsWhatsappRouteImport.update({
    id: '/modules/integrations-whatsapp',
    path: '/modules/integrations-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesEventsRoute = ModulesEventsRouteImport.update({
  id: '/modules/events',
  path: '/modules/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/events': typeof ModulesEventsRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/events': typeof ModulesEventsRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/events': typeof ModulesEventsRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modules/$module'
    | '/modules/events'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modules/$module'
    | '/modules/events'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
  id:
    | '__root__'
    | '/'
    | '/modules/$module'
    | '/modules/events'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
  ModulesEventsRoute: typeof ModulesEventsRoute
  ModulesIntegrationsWhatsappRoute: typeof ModulesIntegrationsWhatsappRoute
  ModulesTemplatesEmailRoute: typeof ModulesTemplatesEmailRoute
  ModulesTemplatesSmsRoute: typeof ModulesTemplatesSmsRoute
  ModulesTemplatesWhatsappRoute: typeof ModulesTemplatesWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-whatsapp': {
      id: '/modules/templates-whatsapp'
      path: '/modules/templates-whatsapp'
      fullPath: '/modules/templates-whatsapp'
      preLoaderRoute: typeof ModulesTemplatesWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-sms': {
      id: '/modules/templates-sms'
      path: '/modules/templates-sms'
      fullPath: '/modules/templates-sms'
      preLoaderRoute: typeof ModulesTemplatesSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-email': {
      id: '/modules/templates-email'
      path: '/modules/templates-email'
      fullPath: '/modules/templates-email'
      preLoaderRoute: typeof ModulesTemplatesEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/integrations-whatsapp': {
      id: '/modules/integrations-whatsapp'
      path: '/modules/integrations-whatsapp'
      fullPath: '/modules/integrations-whatsapp'
      preLoaderRoute: typeof ModulesIntegrationsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/events': {
      id: '/modules/events'
      path: '/modules/events'
      fullPath: '/modules/events'
      preLoaderRoute: typeof ModulesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesModuleRoute: ModulesModuleRoute,
  ModulesEventsRoute: ModulesEventsRoute,
  ModulesIntegrationsWhatsappRoute: ModulesIntegrationsWhatsappRoute,
  ModulesTemplatesEmailRoute: ModulesTemplatesEmailRoute,
  ModulesTemplatesSmsRoute: ModulesTemplatesSmsRoute,
  ModulesTemplatesWhatsappRoute: ModulesTemplatesWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
